# Generated by Django 3.1.6 on 2021-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('male', models.CharField(max_length=30)),
                ('female', models.CharField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('course', models.TextField(max_length=30)),
                ('photo', models.ImageField(upload_to='Register')),
                ('ano', models.CharField(max_length=20)),
                ('pno', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=30)),
            ],
        ),
    ]
