# Generated by Django 3.1.6 on 2021-02-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='lname',
        ),
    ]
