# Generated by Django 3.1.6 on 2021-02-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210222_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='desc',
        ),
        migrations.AddField(
            model_name='student',
            name='activity',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='collage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='job',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='package',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='percent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ano',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
