# Generated by Django 3.1.6 on 2021-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('collage', models.CharField(max_length=50, null=True)),
                ('ano', models.CharField(max_length=50, null=True)),
                ('phno', models.CharField(max_length=50, null=True)),
                ('exp', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
