# Generated by Django 3.1.6 on 2021-02-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
