# Generated by Django 3.1.6 on 2021-02-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210226_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
